apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-scrt
              key: MYSQL_ALLOW_EMPTY_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: data-scrt
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-scrt
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-scrt
              key: MYSQL_ROOT_PASSWORD
        image: olgatyshkevych/quotes-data:v1
        name: db
        ports:
        - containerPort: 3306
        resources: {}
      #   volumeMounts:
      #     - mountPath: /data/db
      #       name: data-volume
      # volumes:
      #   - name: data-volume
      #     persistentVolumeClaim:
      #       claimName: data-pvc
      restartPolicy: Always
status: {}