version: "3"
services:

  front:
    image: "olgatyshkevych/quotes-front:v1"
    ports:
      - "3001:3001"
    networks:
      - myapp

  api:
    image: "olgatyshkevych/quotes-back:v1" 
    ports:
      - "3000:3000"
    networks:
      - myapp

  db:
    image: "olgatyshkevych/quotes-data:v1"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    image: "olgatyshkevych/quotes-data-script:v1"
    networks:
      - myapp

networks:
  myapp: